// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4UZfp6cIXGPTpYBoQw00DvXi5ykw_J0',
    appId: '1:569418334295:web:98f9b46e5c7cfc11c4e312',
    messagingSenderId: '569418334295',
    projectId: 'asynconf-8700c',
    authDomain: 'asynconf-8700c.firebaseapp.com',
    storageBucket: 'asynconf-8700c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0K9vdJi0-PfNQvrxx9096XH6-n3cQfXI',
    appId: '1:569418334295:android:9cf8f26c4b44928cc4e312',
    messagingSenderId: '569418334295',
    projectId: 'asynconf-8700c',
    storageBucket: 'asynconf-8700c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBggo4GMAG31NCLa-fuCuOf1qmSGiuSC4g',
    appId: '1:569418334295:ios:d8c935f7e04d2d42c4e312',
    messagingSenderId: '569418334295',
    projectId: 'asynconf-8700c',
    storageBucket: 'asynconf-8700c.appspot.com',
    iosClientId: '569418334295-hrsh336n4ps2o1513t1olhoig7loal7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.asyncof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBggo4GMAG31NCLa-fuCuOf1qmSGiuSC4g',
    appId: '1:569418334295:ios:7e47c890a418c40dc4e312',
    messagingSenderId: '569418334295',
    projectId: 'asynconf-8700c',
    storageBucket: 'asynconf-8700c.appspot.com',
    iosClientId: '569418334295-g3und6ahd7addvu6jqv71dbthf2dub5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.asyncof.RunnerTests',
  );
}
